In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('dataset/events.csv', sep=',')
df

             timestamp  visitorid event  itemid  transactionid
0        1433221332117     257597  view  355908            NaN
1        1433224214164     992329  view  248676            NaN
2        1433221999827     111016  view  318965            NaN
3        1433221955914     483717  view  253185            NaN
4        1433221337106     951259  view  367447            NaN
...                ...        ...   ...     ...            ...
2756096  1438398785939     591435  view  261427            NaN
2756097  1438399813142     762376  view  115946            NaN
2756098  1438397820527    1251746  view   78144            NaN
2756099  1438398530703    1184451  view  283392            NaN
2756100  1438400163914     199536  view  152913            NaN

[2756101 rows x 5 columns]

In [21]:
# Sort entries by visitorid and time
df = df.sort_values(by=['visitorid', 'timestamp'])
# Change time to readable date & time 
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
df

                      timestamp  visitorid event  itemid  transactionid
1361687 2015-09-11 20:49:49.439          0  view  285930            NaN
1367212 2015-09-11 20:52:39.591          0  view  357564            NaN
1367342 2015-09-11 20:55:17.175          0  view   67045            NaN
830385  2015-08-13 17:46:06.444          1  view   72028            NaN
742616  2015-08-07 17:51:44.567          2  view  325215            NaN
...                         ...        ...   ...     ...            ...
206556  2015-06-10 21:46:08.922    1407575  view  121220            NaN
47311   2015-06-03 15:01:29.991    1407576  view  356208            NaN
1762583 2015-05-17 21:48:04.867    1407577  view  427784            NaN
1744277 2015-05-17 01:21:23.288    1407578  view  188736            NaN
482559  2015-06-24 22:22:06.978    1407579  view    2521            NaN

[2756101 rows x 5 columns]

In [22]:
sequences = df.groupby('visitorid')['event'].apply(list)
sequences

visitorid
0                                        [view, view, view]
1                                                    [view]
2          [view, view, view, view, view, view, view, view]
3                                                    [view]
4                                                    [view]
                                 ...
1407575                                              [view]
1407576                                              [view]
1407577                                              [view]
1407578                                              [view]
1407579                                              [view]
Name: event, Length: 1407580, dtype: object