In [5]:
import pandas as pd

In [9]:
df = pd.read_csv('dataset/events.csv', sep=',')
df

             timestamp  visitorid event  itemid  transactionid
0        1433221332117     257597  view  355908            NaN
1        1433224214164     992329  view  248676            NaN
2        1433221999827     111016  view  318965            NaN
3        1433221955914     483717  view  253185            NaN
4        1433221337106     951259  view  367447            NaN
...                ...        ...   ...     ...            ...
2756096  1438398785939     591435  view  261427            NaN
2756097  1438399813142     762376  view  115946            NaN
2756098  1438397820527    1251746  view   78144            NaN
2756099  1438398530703    1184451  view  283392            NaN
2756100  1438400163914     199536  view  152913            NaN

[2756101 rows x 5 columns]

In [13]:
df = df.sort_values(by=['visitorid', 'timestamp'])
df

             timestamp  visitorid event  itemid  transactionid
1361687  1442004589439          0  view  285930            NaN
1367212  1442004759591          0  view  357564            NaN
1367342  1442004917175          0  view   67045            NaN
830385   1439487966444          1  view   72028            NaN
742616   1438969904567          2  view  325215            NaN
...                ...        ...   ...     ...            ...
206556   1433972768922    1407575  view  121220            NaN
47311    1433343689991    1407576  view  356208            NaN
1762583  1431899284867    1407577  view  427784            NaN
1744277  1431825683288    1407578  view  188736            NaN
482559   1435184526978    1407579  view    2521            NaN

[2756101 rows x 5 columns]

In [16]:
sequences = df.groupby('visitorid')['event'].apply(list)
sequences.head(30)

visitorid
0                                   [view, view, view]
1                                               [view]
2     [view, view, view, view, view, view, view, view]
3                                               [view]
4                                               [view]
5                                               [view]
6            [addtocart, view, view, view, view, view]
7                                   [view, view, view]
8                                               [view]
9                                               [view]
10                                              [view]
11                                              [view]
12                                              [view]
13                                        [view, view]
14                                              [view]
15                                              [view]
16                                              [view]
17                                              [view]
18                                              [view]
19                                              [view]
20                                              [view]
21                                              [view]
22                                        [view, view]
23                                  [view, view, view]
24                                        [view, view]
25                                              [view]
26                                              [view]
27                                              [view]
28                                              [view]
29                                              [view]
Name: event, dtype: object